### ISSUE TITLE
not feeling aLive enough

### ISSUE THREAD

**Issue by YoniLahav** [live-section/live#1]
Hey, first of all I gotta say this looks fantastic. Great concept, can't wait for this to go Live!
Alas, I have a small issue with the idea. I really just don't feel alive enough to actually join Live, you know?
Like you said, everybody dies, so why not just end it quickly? Why should I actually join you in this pathetic quest?
This is absurd.
Are you really THAT disconnected?
Fix yourself.

★✰✰✰✰ Terrible

**Comment by deankevorkian** [comment]
Yes thank you, we will dive deeper into this problem and work to fix it. Thank you for your feedback.
